### ISSUE TITLE
[BUG] Multipolygon relation are not rendered

### ISSUE THREAD

**Issue by Stefal** [open-indoor/openindoor6#52]
Example : https://app.openindoor.io/#20.33/48.8405298/2.3208004/7.8/32
The "Paname" bar is not rendered, and all other multipolygon indoor rooms inside Montparnasse train station.
![image](https://user-images.githubusercontent.com/8255984/170837169-8272b875-a347-4cd7-96ac-6030000b5668.png)

https://www.osm.org/relation/14130160

**Comment by cigone-openindoor** [comment]
Thank you Stefal, good feedback.
The issue came from API that render data, that excluded relations from extracted data.
It's fixed now.

<img width="738" alt="Capture d’écran 2022-05-29 à 07 39 09" src="https://user-images.githubusercontent.com/69067574/170853976-36116352-bc9e-44c6-b377-d418c4a95d9b.png">
